global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'eauction-backend-cluster'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'app1:9091'
          - 'app2:9091'